### ISSUE TITLE
aqcuire → acquire でしょうか

### ISSUE THREAD

**Issue by tokugh** [oreilly-japan/conc_ytakano#12]
aqcuire → acquire でしょうか。
3_3_1_spinlock_1.c
3_3_1_spinlock_2.c
3_3_1_use_spinlock.c
3_4_1_semaphore_llsc.S
3_4_semaphore_llsc.c
3_4_semaphore.c
3_7_1_rwlock_spin.c
3_4/semtest.c
4_4/reent.c

**Comment by ytakano** [comment]
Yes!
修正しておきます！

**Comment by ytakano** [comment]
修正しました。ありがとうございます。
