### ISSUE TITLE
chap4/ch4_6_signal_c/signal_c.c の内容が chap4/4.5/spurious.c と同一になってしまっています

### ISSUE THREAD

**Issue by south37** [oreilly-japan/conc_ytakano#14]
## 観測した事象
2021年8月29日時点でこのレポジトリにコミットされた [chap4/ch4_6_signal_c/signal_c.c](https://github.com/oreilly-japan/conc_ytakano/blob/main/chap4/4.6/ch4_6_signal_c/signal_c.c) の内容が、 [chap4/4.5/spurious.c](https://github.com/oreilly-japan/conc_ytakano/blob/main/chap4/4.5/spurious.c) と同一になってしまっているようです。
これは「4.5 擬似覚醒」に掲載されていたコードであるため、期待とは違う内容になっています。

## 期待した事象
chap4/ch4_6_signal_c/signal_c.c には、書籍「並行プログラミング入門」の「4.6 シグナル」における p.128 のコード、もしくは p.129-p.130 のコードが掲載されることを期待しました。

**Comment by ytakano** [comment]
ありがとうございます！
後ほど修正します。

**Comment by ytakano** [comment]
修正しました。

**Comment by south37** [comment]
ありがとうございます！ 😄
