### ISSUE TITLE
4.7節 dmb st 命令の挙動

### ISSUE THREAD

**Issue by takenobu-hs** [oreilly-japan/conc_ytakano#21]
細かいのですが、4.7節の`dmb st`命令の挙動が、Arm v8仕様と少し異なっているようです。
`dmb st`命令は、store - store 命令間の順序付けのみを行うので、後続のload命令については前倒しが可能です。

#### 要修正と思われる箇所

* 図4-9 の中央の`dmb st`の図:
  正しくは、後続(右側)のldr の矢印は、垂直線を越えて前方(左)側に入り込みます。

* 表4-3 の2行目の`dmb st`の行:
  ```diff
  - この命令以降のメモリ読み書き命令が
  + この命令以降のメモリ書き込み命令が
  ```

* p.133の本文:
  図4-9の直下の本文説明での`st`の説明について、同様です。

#### 参考仕様書

参考にしたArm v8の仕様書は以下となります:
* Arm Architecture Reference Manual Armv8 の、B2.3.10節の Table B2-1
  * https://developer.arm.com/documentation/ddi0487/latest

* または、以下のページの Using barriers の節
  * https://developer.arm.com/documentation/100941/0100/Barriers

**Comment by ytakano** [comment]
ありがとうございます！
後ほど正誤表に追記します。

**Comment by takenobu-hs** [comment]
理論から抽象度の高いソフトレベルからハードの詳細レベルまで、明確で本質的で簡潔で網羅的で本当に素晴らしい本です！

**Comment by ytakano** [comment]
ありがとうございます。そう言って頂けると、執筆して良かったと思い励みになります。
正誤表にも追記しました。
