### ISSUE TITLE
typo? 3.4.2　POSIXセマフォ

### ISSUE THREAD

**Issue by shinji-dosaka** [oreilly-japan/conc_ytakano#22]
>     sem_t *s = sem_open('/mysemaphore', O_CREAT, 0066, 3);

> 第3引数の0066はパーミッションであり、これはUNIX系OSのファイルパーミッションと同じである。ここでは、OSプロセスの所有者とグループが読み書き可能であると指定している。

「プロセスの所有者とグループが読み書き可能であると指定」する場合、
`0066`ではなく、`0660`ではないでしょうか?

所有者にパーミッションがなくても、グループにパーミッションがあるので動作しますが。

**Comment by ytakano** [comment]
ありがとうございます。ご指摘通り`0660`のtypoです。後ほど正誤表に追記いたします。

**Comment by ytakano** [comment]
正誤表に追記しました。ありがとうございます！
