### ISSUE TITLE
typo? 8.2.8 評価戦略

### ISSUE THREAD

**Issue by shinji-dosaka** [oreilly-japan/conc_ytakano#23]
> (λx.M N )という式があった場合、先にβ簡約を行うのか、それとも M の評価を先に行うのかという、2 種類の評価戦略が考えられる。先にβ簡約を行う戦略を、正規順序の評価(normal- order evaluation)と呼び、先に引数 M の評価を行う戦略を、作用的順序の評価(applicative- order evaluation)と呼ぶ。

「M の評価を先に行うのか」と「先に引数 M の評価を行う戦略を」の2箇所について、
引数はMではなくNでは?

**Comment by ytakano** [comment]
ありがとうございます！
ご指摘通りNが正しいです。正誤表に追加しました。
