### ISSUE TITLE
3.8.2 条件変数 wait_white の述語

### ISSUE THREAD

**Issue by melpon** [oreilly-japan/conc_ytakano#25]
P.93、3.8.2 条件変数 の

> `wait_white` 関数では、第２引数で渡される述語が false となる間待機する。

ですが、Rust のドキュメントを見る限り、述語が false の間待機（true になるまで待機）ではなく、述語が false になるまで待機（true の間待機）のようなので、

> `wait_white` 関数では、第２引数で渡される述語が false となるまで待機する。

が正しいのではないかと思いました。

**Comment by ytakano** [comment]
正誤表に追加しました。ありがとうございます！
