### ISSUE TITLE
typo? 表A-14 AArch64の条件セット命令

### ISSUE THREAD

**Issue by shinji-dosaka** [oreilly-japan/conc_ytakano#26]
> csetm if cond then 0 のビット反転 else reg = 0

「0 のビット判定」は「reg = -1」もしくは「reg = 0 のビット反転」では?
(-1は2の補数で0のビット反転ですが、-1で良いかと思います。)

see.
https://developer.arm.com/documentation/100069/0608/A64-General-Instructions/CSETM
> Operation
> Conditional Set Mask sets all bits of the destination register to 1 if the condition is TRUE, and otherwise sets all bits to 0.
>
> Rd = if cond then -1 else 0, where R is either W or X.

**Comment by ytakano** [comment]
ありがとうございます。reg = -1として、正誤表に追記しました。
