### ISSUE TITLE
typo? 例 A-1 fizzbuzz.S

### ISSUE THREAD

**Issue by shinji-dosaka** [oreilly-japan/conc_ytakano#27]
>    // if x0 % 5 != 0 then go to .Lend1
>    mov　　x20, #5
>    udiv　 x19, x0, x20
>    msub　 x19, x19, x20, x0
>    cmp　　x19, xzr // x0 % 3 == 0

最後のコメントは「x0 % 5 == 0」ですね。

(ところで、FizzBuzzは3,5,15で割り切れない場合は数値を出力するのが普通では?と思うのですが、
数値を文字に変換して出力するのがちょっと面倒なので省略しているんですね。)

**Comment by ytakano** [comment]
ありがとうございます。x0 % 5 == 0として、正誤表に追記しました。

（ご指摘通り、数値を出力するのが正しいのですが、ここでは省略しています）
