### ISSUE TITLE
comment p.328 次の表とは?

### ISSUE THREAD

**Issue by shinji-dosaka** [oreilly-japan/conc_ytakano#28]
> ここで例として、符号なしの比較命令を考えてみると、比較命令実行後はオペランドの値によ 
> り、ゼロフラグ(Z)とキャリーフラグ(C)は次の表のように変化する。したがって、これら条件
> フラグをチェックすることで、a > b や a ≦ b などを検査できることがわかる。

「次の表のように」とありますが、次の表がないようです。

表を追加すると、表番号がずれて、表参照の番号もずれてしまってめんどくさそうですが。

**Comment by ytakano** [comment]
ありがとうございます。表を正誤表に追記しました。

本文修正は、表を追加するか、文章を加筆修正するかで対応したいと思います。

https://github.com/oreilly-japan/conc_ytakano/blob/main/errata.md#%E4%BB%98%E9%8C%B2ap328cmp%E5%91%BD%E4%BB%A4%E3%81%AE%E6%9D%A1%E4%BB%B6%E3%83%95%E3%83%A9%E3%82%B0%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
