### ISSUE TITLE
typo? 表B-3 データコピー命令

### ISSUE THREAD

**Issue by shinji-dosaka** [oreilly-japan/conc_ytakano#30]
> popq r/m | D = (%rsp); %rsp = %rsp + 8 | スタックからのpop

1行目の例(「r/m = S」)を見ると、「r/m = (%rsp);」ですかね。

**Comment by ytakano** [comment]
`r/m = (%rsp);`として正誤表に追記しました。

多数の正誤報告ありがとうございます！
