### ISSUE TITLE
一章 P.12 図1-8の説明文

### ISSUE THREAD

**Issue by pocari** [oreilly-japan/conc_ytakano#33]
> クロック1のときに、まず、IDがメモリ上から命令を読み込んできて

とあるのですが、命令を読み込んでくるのは IF になるんでしょうか？

**Comment by ytakano** [comment]
はい。ご指摘通りIFの誤りです。後ほど正誤表に追記いたします。

**Comment by ytakano** [comment]
正誤表に追記しました。ありがとうございます！
