### ISSUE TITLE
typo? epub 全体

### ISSUE THREAD

**Issue by shinji-dosaka** [oreilly-japan/conc_ytakano#43]
C/Rustのコード部分の文字列リテラルですが、
PDFはダブルクォートで囲まれていますが、
epubがシングルクォートになっているようです。

例えば、
2.2.1.1　スレッドの生成と終了待ち合わせ
```
        printf('id = %d, i = %d\n', id, i);
```

**Comment by ytakano** [comment]
ありがとうございます。
正誤表に追記しました。

https://github.com/oreilly-japan/conc_ytakano/blob/main/errata.md#epub%E7%89%88%E3%81%AE%E6%96%87%E5%AD%97%E5%88%97%E8%A1%A8%E8%A8%98%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by ytakano** [comment]
ePub版のソースコードにある文字列リテラルが、ダブルクォーテーションではなく、シングルクォーテーションとなっていると報告頂きましたが、こちらの環境では、ダブルクォーテーションとなっているようです。

以下はMacのiBookでの表示となります。
![スクリーンショット 2021-09-29 11 01 34](https://user-images.githubusercontent.com/29608/135190476-0b32a9f2-80fa-4888-be27-d9c2005e05db.png)

ChromeのCloud ePub Readerでもダブルクォーテーションのようです。

すみませんが、ご利用のePubリーダをお教え頂けますでしょうか。

**Comment by shinji-dosaka** [comment]
FirefoxのEPUBReaderを使っていました。

https://addons.mozilla.org/ja/firefox/addon/epubreader/

確かに、epubをzip展開して見てみると、ちゃんとダブルクォートになっていますね。

oreilly-978-4-87311-959-5e/item/xhtml/p-*.xhtml

確認不足で申し訳ありませんでした。

**Comment by shinji-dosaka** [comment]
<img width="957" alt="mac_firefox_epubreader" src="https://user-images.githubusercontent.com/7134577/135232445-d40bea61-e230-45d1-851b-a9a70d1b8809.png">

**Comment by ytakano** [comment]
いえいえ。色々とご指摘、コメントありがとうございます！
