### ISSUE TITLE
コードの修正ミスでしょうか?

### ISSUE THREAD

**Issue by falloutkid** [oreilly-japan/conc_ytakano#45]
P58の最後のコードの関数の戻り値はboolですが、P59.の説明文では

>ただし、C 言語ではゼロが false、非ゼロが true を意味するため、返り値の型は int 型としている

となっています。

**Comment by ytakano** [comment]
ありがとうございます！
こちらの文章は必要ないため、不要な文章として正誤表に追記しました。

もともとintにしていたのですが、最近はC言語でもboolが利用できるため変更したのでした。
