### ISSUE TITLE
comment 4章 コメント(2点)

### ISSUE THREAD

**Issue by shinji-dosaka** [oreilly-japan/conc_ytakano#50]
友人と読書会でこの本を読んでいるのですが、何点か感想というかコメントが上がったので共有します。

## 1. 銀行家のアルゴリズムでの食事する哲学者問題のコード

p.121 Rustコードでの初期化コードですが、全部1が並んでいてちょっとわかりにくいです。
哲学者を3以上にすると、すこし可読性が上がるのではないでしょうか?
```
    let banker = Banker::<2, 2>::new([1, 1], [[1, 1], [1, 1]]);
```
↓
```
    let banker = Banker::<3, 3>::new([1, 1, 1],
        [[1, 1, 0], [0, 1, 1], [1, 0, 1]]);
```

## 2. シグナルセーフでない関数呼び出し

p.128 シグナルハンドラでシグナルセーフでないpthread_mutex_lockを呼ぶこと自体
ダメなことを伝えたほうがよいのではないでしょうか?

例えばLinuxだとmanでシグナルセーフな関数の一覧が確認できます。
https://man7.org/linux/man-pages/man7/signal-safety.7.html

**Comment by ytakano** [comment]
貴重なコメントありがとうございます。
機会があれば反映したいと思います。

確かに、シグナルセーフな関数なども説明するとよいと思いました。
