### ISSUE TITLE
3.3.1 スピンロックのコード例が正しくlock取得できていない

### ISSUE THREAD

**Issue by convto** [oreilly-japan/conc_ytakano#63]
該当部分はここです
https://github.com/oreilly-japan/conc_ytakano/blob/main/chap3/3.3/3_3_1_spinlock_1.c#L4

test_and_setはlockを獲得したときはfalseを返却するのでwhileでロック獲得を待ち合わせるためには以下のように

```c
while (!test_and_set(lock));
```

とする必要があるように思います。

なお直後のコード例ではそのようにロック取得の判断をしています
https://github.com/oreilly-japan/conc_ytakano/blob/main/chap3/3.3/3_3_1_spinlock_2.c#L4-L8

**Comment by ytakano** [comment]
ありがとうございます！後ほど修正いたします。

**Comment by ytakano** [comment]
ソースコードを修正し、正誤表に追記しました。ありがとうございます。
https://github.com/oreilly-japan/conc_ytakano/blob/main/errata.md

**Comment by convto** [comment]
ご対応ありがとうございました！

**Comment by convto** [comment]
すみません、 https://github.com/oreilly-japan/conc_ytakano/issues/65 で指摘されているように僕の確認不足でした。
お騒がせして申し訳ないです:bow:

**Comment by ytakano** [comment]
いえいえ、プログラミングなんてバグがあって当たり前です。
また気がついたところがあれば、これに懲りず遠慮なくお伝えください！
