### ISSUE TITLE
3.3.1 スピンロックのコード例の正誤表が誤っている

### ISSUE THREAD

**Issue by ouchi2501** [oreilly-japan/conc_ytakano#65]
下記issueで修正されている内容ですが、本の内容が正しいように思いました
https://github.com/oreilly-japan/conc_ytakano/issues/63

while文はtrueである限りloopし続けるため `!` を入れてしまうと待ち受けできなくなるかと思います
本に記載の内容である
```c
 while (test_and_set(lock)); 
```

のままで正しいように思いました

また、issueで指摘されている下記部分ですが
https://github.com/oreilly-japan/conc_ytakano/blob/417ee27675258103598cd9fb087c031fc73f8ad9/chap3/3.3/3_3_1_spinlock_2.c#L4-L8

こちらもwhile部分はlockをそのまま比較していて、falseの場合はbreakするようになっているので、単純に直後のコード例に `!` がついているからといって件のコードに適用は出来ないかと思いました
```c
if (!test_and_set(lock))
            break;
```

**Comment by ytakano** [comment]
ありがとうございます！
確認不足でした。修正しました。

**Comment by ouchi2501** [comment]
修正されていることを確認しました
ご対応ありがとうございます!
