### ISSUE TITLE
[p.158] eventfdでの通知について

### ISSUE THREAD

**Issue by KeiichiHirobe** [oreilly-japan/conc_ytakano#67]
p.158に

> 本実装ではこの関数を利用してeventfdに1を書き込むことでIOSelectorへ通知し、IOSeclectorは読み込み後に0を書き込むことでイベント通知を解除する。

とありますが、0を書き込んでいる箇所を見つけられませんでした。

また、[eventfd](https://linuxjm.osdn.jp/html/LDP_man-pages/man2/eventfd.2.html)の挙動として、

writeは
> write(2) は、引数のバッファーで渡された 8 バイトの整数値をカウンターに加算する。

readは
> EFD_SEMAPHORE が指定されておらず、eventfd カウンターが 0 以外の値の場合、 read(2) はカウンター値を格納した 8 バイトの値を返し、 カウンター値は 0 にリセットされる。

とあることから、0を書き込むことで解除はされないのではと思いました。

https://github.com/oreilly-japan/conc_ytakano/blob/16643a2eb00697b991a8763d537e291fa24a6877/chap5/5.3/ch5_3_2_ioselect/src/main.rs#L147

のwhile文直下に、`read_eventfd(fd)` のようなコードが必要ではないでしょうか。

**Comment by ytakano** [comment]
ありがとうございます！
確認して正誤表に記載します。

**Comment by ytakano** [comment]
正誤表に追記しました。
https://github.com/oreilly-japan/conc_ytakano/blob/main/errata.md

また、ソースコードも修正しました。
https://github.com/oreilly-japan/conc_ytakano/blob/379a4c115e5c5e096aa347c17e4e14cc969aa306/chap5/5.3/ch5_3_2_ioselect/src/main.rs#L146-L147

ありがとうございます。
