### ISSUE TITLE
[p.224]2番の説明が一部誤っている

### ISSUE THREAD

**Issue by KeiichiHirobe** [oreilly-japan/conc_ytakano#70]
p.224の2番にて

> ここでErrが返ってくるということは、ifの条件式(4行目)と、この行の間に、他のスレッドによってlast変数が更新されたということになる

とありますが、その可能性もありますが、ifの条件式(4行目)以前に既にlast変数が更新されている可能性もあると思います。
lock関数にてlast変数が更新されたが、next変数が未更新の場合があり得るためです。

細かい誤りなので、正誤表に記載しなくても良いかもしれませんが、気になったので念の為指摘させていただきました。

**Comment by ytakano** [comment]
ありがとうございます！
もし増刷されたら、修正したいと思います。
