### ISSUE TITLE
[p.220]チケットロックでのオーバヘッドについて

### ISSUE THREAD

**Issue by KeiichiHirobe** [oreilly-japan/conc_ytakano#71]
連投かつ細かい指摘で恐縮です。p.220について、

> 複数のCPUで同一アドレスを排他に設定し合うと、メモリの読み書き権限を奪い合うことになり、それがオーバヘッドとなる

とありますが、チケットロックの実装を読む限り複数のCPUで同一アドレスを排他に設定し合うことはなさそうに思いました。

前提として、

* この文脈での同一アドレスとは、`turn`のことを指している
* `fetch_add`のようなatomicなread-modify-writeはCPUを排他に設定するが、単純な`load`は排他設定は不要

という理解でいます。
これが正しければ、

`turn`は複数スレッドからspinで`load`され、drop時に`fetch_add`されているのでオーバヘッドが高いものの、CPUを排他に設定するのは`drop`のみであり、単一CPUのみではないかと思った次第です。

**Comment by ytakano** [comment]
ありがとうございます！
ご指摘通りです。

複数のCPUが排他に設定し合うのではなく、1つのCPUが排他に設定し、それ以外のCPUがloadするため排他設定が解除されるため、オーバーヘッドとなる、というように機会があれば修正したいと思います。
