### ISSUE TITLE
8.2 節のλ式の括弧の省略方法

### ISSUE THREAD

**Issue by hiratara** [oreilly-japan/conc_ytakano#74]
8.2 節を読んでいるのですが、λ式の括弧の省略方法が [TAPL](https://www.ohmsha.co.jp/book/9784274069116/) と違うようなのですが、このような流儀もあるのでしょうか？

TAPL 内の括弧の省略法について引用すると、

> たくさんの括弧を書かなくてもよいように、一列にラムダ項を書く際に二つの慣習を採用する。まず一つ目に、関数適用は左結合とする。つまり、s t u は (s t) u と同じ木を表す。
> 二つ目に、抽象の本体はできる限り右側へ拡大する。したがって、例えば、λx. λy. x y x は以下に示す λx. (λy. ((x y) x)) と同じ木を表す。

とあります。

本書第一刷の 8.2.1 節の P.266 では、 (λx.M a) を関数適用の記法として採用していますが、 TAPL のルールに則ってこのλ式を解釈して括弧を補うと「抽象の本体はできる限り右側へ拡大する」ため、 λx. (M a) となります。これは意図したものとは違うはずで、 (λx.M) a と書くのが一般的ではないでしょうか。

以降のλ式についても同様ですので、採用している記法が本当に正しいか、確認して頂けますでしょうか。

**Comment by ytakano** [comment]
ありがとうございます。

ご指摘通り、TAPLや一般的な構文とは異なります。統語論は若干違いますが、意味論は同じかと思います。
この構文にすることで、次のメリットとデメリットがあります。

**メリット** : 式から構文木が一意に定まるため、初学者にわかりやすい。関数適用の括弧づけに混乱が生じにくい

**デメリット** : 括弧が多くなる。一般的な構文とは異なる。

本書では、上記メリットを考慮し、この構文としました。
アクターモデルの節では、λ計算の関数適用をさらに修正し、一般的なプログラミング言語の関数適用のように修正したバージョンが登場します。どちらも構文定義は明確にしてありますので、それら定義を参照して頂ければと思います。

よろしくお願いいたします。

**Comment by hiratara** [comment]
なるほど、ありがとうございます。

参考までに、本書籍と同じ記法を採用している参考文献などあれば、参考にしたいので教えて頂けますか。特にないようでしたら、意図的であることはわかりましたのでこのままクローズしていただいても構いません。

**Comment by ytakano** [comment]
こちらこそ、詳細までお読み頂きありがとうございます。
8.2のλ計算の構文は、本書独自で、8.3アクターモデルのλ計算は『Programming Distributed Computing Systems』に記載があります。

**Comment by hiratara** [comment]
ありがとうございます。承知致しました。

こちらでクローズしておきます 🙇
