### ISSUE TITLE
p.302 証明の 2. に書かれているα変換

### ISSUE THREAD

**Issue by hiratara** [oreilly-japan/conc_ytakano#76]
c̅x.0 | c&lt;y>.y̅z.0 → x̅z.0 の証明の 2. でα変換をしていますが、これは必要でしょうか。

\3. の導出で 2. を要求していますが、 INTR 規則を使っているだけで 2. の事実は使っていないように見えました。

**Comment by ytakano** [comment]
ありがとうございます！
たしかに、2. は必要ないと思います。正誤表に追記します。

**Comment by hiratara** [comment]
b697c2fdcd11b44caa59f8f4aecd1ede1ce384b3 で修正されていますので、クローズさせていただきます 🙇
