### ISSUE TITLE
TSOのメモリオーダリングについて

### ISSUE THREAD

**Issue by kons-9** [oreilly-japan/conc_ytakano#83]
TSOのメモリオーダリングはload-store(R->W)の並び替えでは起きないと思います。
そのため(第一版ですが)p'134の表は間違っていると感じます。

参考
https://www.cl.cam.ac.uk/~pes20/weakmemory/cacm.pdf
のexample 8-2から8-4

**Comment by ytakano** [comment]
ありがとうございます。
R→Wではなく、W→Rに思います。
後ほど、正誤表に掲載します。

**Comment by ytakano** [comment]
正誤表に追記しました。ありがとうございます！
